### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by NiHuShu** [ripdajacker/xpad-avr#1]
When trying to compile there's error "string.h: No such file or directory"

**Comment by ripdajacker** [comment]
What OS? Which compiler?

It would seem you are missing avr-libc

**Comment by NiHuShu** [comment]
Oh ok. It works now. I thought that you only need gcc-avr. Now if I compile it and flash to Arduino without modifying anything that this will do? I'm trying to make PS2 controller to Xbox adapter using Arduino Leonardo so maybe you could help me?

**Comment by ripdajacker** [comment]
If you run make you will get a hex file. You can burn that on any atmega32u4 based board, Arduinos included.

Interfacing with a PS2 controller can be done with an Arduino, I am not sure how though. You will want to do some research there. As far as I remember the PS1/2 controllers are clocked by the host, so you should be able to do it between the 1ms USB reports of the xpad-avr code.

**Comment by ripdajacker** [comment]
But to be fair the 1ms may be too short a period to do proper debouncing of the keys. There are projects out there that use the PS2 controller with an arduino.

**Comment by NiHuShu** [comment]
Okay, so this is pretty easy library for using a PS2 controller with Arduino https://github.com/madsci1016/Arduino-PS2X . The question is how can I use xpad with Arduino IDE or how to use PS2X with xpad?

**Comment by ripdajacker** [comment]
The xpad code won't compile in arduino without some changes (I am not sure which), since it is written with only vanilla AVR GCC and LUFA.
You can most certainly port the PS2 library to vanilla AVR, but I would suggest you go out and buy a pre-built adapter like this: https://www.ebay.co.uk/itm/PS2-to-Xbox-Controller-Adapter-Converter-Cable-Cord-for-Microsoft-Xbox-Console/231798187231?hash=item35f83fa4df:g:OucAAOSwBNxalVJH

If you really want to do it yourself, I suggest you search for "ps2 controller AVR".
A quick search found this: https://sites.google.com/site/mrdunk2/ps2controlleronanavr

The vanilla AVR is a little bit more verbose, but you will be able to easily integrate the code into xpad-avr.

**Comment by NiHuShu** [comment]
Ok I have absolutely no idea how to integrate everything but I will try :D

**Comment by ripdajacker** [comment]
If you have some experience in C and some patience you should be able to pull it off :) I would start by making a PS2 controller interface in vanilla AVR. The reason for not using Arduino is that LUFA does not integrate well with Arduino since they have their own USB stack.

The USB code runs once every 1ms giving you a window of approximately 500us between the USB communication to do your stuff. You shouldn't worry about lag that much, the controllers I have only send real controller input data every ~8ms, which gives you a whopping 4ms to read the PS2 input, convert it to xpad-compatible events and send it.
